<?php
$_item = $block->getItem();
$viewModel = $block->getViewModel();

?>
<tr>
    <?php $columns = $block->getColumns();
    $lastItemNumber = count($columns);

    $product = $_item->getProduct();
    if (is_object($product) && $viewModel->isEnbaled()) { ?>
        <?php
            $image_url = $viewModel->getImageUrl($product);
            $largeImage = $viewModel->getImageUrlLarge($product);
            $images = $viewModel->getAllImages($product);
        ?>
        <td class="<?= /* @noEscape */
        $columns['product_img'] ?>">
            <img id="inline-image-<?=$product->getId(); ?>" src="<?php echo $image_url; ?>"/>
            <div id="myModal<?=$product->getId(); ?>" class="modal">
                <div class="slider image-slider<?=$product->getId(); ?>">
                    <div>
                        <img class="image_l<?=$product->getId(); ?>" src="<?php echo $largeImage; ?>">
                    </div>
                    <?php foreach($images as $image): ?>
                        <?php
                        $file = $image->getFile();
                        if (strpos( $image_url , $file )) {
                            continue;
                        } ?>
                        <div>
                            <img class="image_l<?=$product->getId(); ?>" src="<?php echo $image->getUrl(); ?>">
                        </div>
                    <?php endforeach; ?>
                </div>
                <div class="caption" id="caption<?=$product->getId(); ?>"><?= $product->getName(); ?></div>
                <div class="click-to-close"><button class="click-to-close<?=$product->getId(); ?>" onclick="$('myModal<?=$product->getId(); ?>').style.display = 'none'">CLOSE</button></div>
            </div>
            <script>
                require([
                    'jquery',
                    'slick'
                ], function ($) {
                    var modal<?=$product->getId(); ?> = document.getElementById("myModal<?=$product->getId(); ?>");
                    var img<?=$product->getId(); ?> = document.getElementById("inline-image-<?=$product->getId(); ?>");
                    var captionText<?=$product->getId(); ?> = document.getElementById("caption<?=$product->getId(); ?>");
                    img<?=$product->getId(); ?>.onclick = function(){
                        modal<?=$product->getId(); ?>.style.display = "block";
                        $('.image-slider<?=$product->getId(); ?>').slick({
                            infinite: true,
                            slidesToShow: 1,
                            slidesToScroll: 1,
                            dots: true,
                            centerMode: true
                        });
                    }
                });
            </script>
        </td>
    <?php } ?>

    <?php foreach ($columns as $columnName => $columnClass): ?>
        <td class="<?= /* @noEscape */
        $columnClass ?>">
            <?php if ($columnClass == "product_img") { ?>
                <?php continue; ?>"
            <?php } else { ?>
                <?php echo $block->getColumnHtml($_item, $columnName); ?>
            <?php } ?>
        </td>
    <?php endforeach; ?>
</tr>
