<?php
$_item = $block->getItem();
$viewModel = $block->getViewModel();

?>
<tr>
    <?php $columns = $block->getColumns();
    $lastItemNumber = count($columns);

    $product = $_item->getProduct();
    $image_url = $viewModel->getImageUrl($product);

    if ($viewModel->isEnbaled()) { ?>
        <td class="<?= /* @noEscape */
        $columns['product_img'] ?>">
            <img id="inline-image-<?=$product->getId(); ?>" src="<?php echo $image_url; ?>"/>
            <div id="myModal<?=$product->getId(); ?>" class="modal">
                <img class="modal-content" src="<?php echo $viewModel->getImageUrlLarge($product); ?>">
                <div class="caption" id="caption<?=$product->getId(); ?>"><?= $product->getName(); ?></div>
                <div class="click-to-close">Click anywhere to close</div>
            </div>
            <script>
                var modal = document.getElementById("myModal<?=$product->getId(); ?>");
                var img = document.getElementById("inline-image-<?=$product->getId(); ?>");
                var captionText = document.getElementById("caption<?=$product->getId(); ?>");
                img.onclick = function(){
                    modal.style.display = "block";
                }
                modal.onclick = function() {
                    modal.style.display = "none";
                }
            </script>
        </td>
    <?php } ?>

    <?php foreach ($columns as $columnName => $columnClass): ?>
        <td class="<?= /* @noEscape */
        $columnClass ?>">
            <?php if ($columnClass == "product_img") { ?>
                <?php continue; ?>"
            <?php } else { ?>
                <?php echo $block->getColumnHtml($_item, $columnName); ?>
            <?php } ?>
        </td>
    <?php endforeach; ?>
</tr>